import os.path


Import(['env', 'common'])

libs = [
    common,
]

providers = [
    'linux',
]

targets = []

for provider in providers:
    target = SConscript(os.path.join(provider, 'SConscript'),
                                     exports=['env', 'common'])

Return(targets)
