import os.path


Import('env')

target = 'tibeebuild'

libs = [
    'boost_program_options',
    'boost_filesystem',
    'boost_system',
]

sources = [
    'main.cpp',
]

app = env.Program(target=target, source=sources, LIBS=libs)

Return('app')
