import os.path


Import(['env', 'common'])

target = 'tibeebuild'

libs = [
    'boost_program_options',
    'boost_filesystem',
    'boost_system',
    common
]

sources = [
    'main.cpp',
]

app_env = env.Clone()

app_env.Append(LIBS=libs)

app = app_env.Program(target=target, source=sources)

Return('app')
