import os.path


Import('env')

target = 'tibeecommon'

trace_sources = [
    'AbstractEventValue.cpp',
    'ArrayEventValue.cpp',
    'DictEventValue.cpp',
    'EnumEventValue.cpp',
    'Event.cpp',
    'EventValueFactory.cpp',
    'FloatEventValue.cpp',
    'SintEventValue.cpp',
    'StringEventValue.cpp',
    'TraceSet.cpp',
    'TraceSetIterator.cpp',
    'UintEventValue.cpp',
    'UnknownEventValue.cpp',
]

state_sources = [
    'AbstractStateValue.cpp',
    'CurrentState.cpp',
    'StateHistorySink.cpp',
]

mq_sources = [
    'AbstractMqSocket.cpp',
    'MqContext.cpp',
    'MqMessage.cpp',
]

subs = [
    ('trace', trace_sources),
    ('state', state_sources),
    ('mq', mq_sources),
]

sources = []
for base, files in subs:
    sources += [os.path.join(base, f) for f in files]

lib = env.Library(target=target, source=sources)

Return('lib')
