import os.path


Import('env')

target = 'tibeecommon'

trace_sources = [
    'AbstractEventValue.cpp',
    'ArrayEventValue.cpp',
    'DictEventValue.cpp',
    'EnumEventValue.cpp',
    'Event.cpp',
    'EventValueFactory.cpp',
    'FloatEventValue.cpp',
    'SintEventValue.cpp',
    'StringEventValue.cpp',
    'TraceSet.cpp',
    'TraceSetIterator.cpp',
    'UintEventValue.cpp',
    'UnknownEventValue.cpp',
]

state_sources = [
    'AbstractStateValue.cpp',
    'CurrentState.cpp',
    'StateHistorySink.cpp',
]

mq_sources = [
    'AbstractMqSocket.cpp',
    'MqContext.cpp',
    'MqMessage.cpp',
]

rpc_sources = [
    'AbstractRpcRequest.cpp',
    'AbstractRpcResponse.cpp',
    'AbstractRpcNotification.cpp',
    'AbstractJsonRpcMessageEncoder.cpp',
    'AbstractJsonRpcMessageDecoder.cpp',
]

subs = [
    ('trace', trace_sources),
    ('state', state_sources),
    ('mq', mq_sources),
    ('rpc', rpc_sources),
]

sources = []
for base, files in subs:
    sources += [os.path.join(base, f) for f in files]

lib_env = env.Clone()

lib_env.ParseConfig('pkg-config --cflags yajl')

lib = lib_env.Library(target=target, source=sources)

Return('lib')
